version: "2.1"

services:
    nginx:
        build: ./nginx/
        ports:
            - 80:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
        networks:
            - server
        depends_on:
            - php

    php:
        build: ./php/
        expose:
            - 9000
        volumes:
            - "${PROJECT_ROOT}:/var/www/html"
        networks:
            - database
            - server
        depends_on:
            - mysql
    # the "mysql" tag is what docker provides as a "host" name to the web directory
    # the actual host is at 127.0.0.1, which needs to be provided here.
    mysql:
        image: mysql:latest
        volumes:
            - data:/var/lib/mysql
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: "halibut"
            MYSQL_DATABASE: "ubersmith"
            MYSQL_USER: "ciscoserret"
            MYSQL_PASSWORD: "halibut"
            MYSQL_HOST: "127.0.0.1"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        networks:
            - database
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql

volumes:
    data:

networks:
    database:
    server: